# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'us_real_estate_screener'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'us_real_estate_screener'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  us_real_estate_screener:
    staging:
      +materialized: table

# Seed configurations
seeds:
  us_real_estate_screener:
    us_zip_codes:
      +column_types:
        zip_code: varchar(10)
        primary_county_fips: varchar(10)
        all_county_fips: text
        active: boolean
      +quote_columns: false
