-- This db script creates the db objects required to house the raw Zillow data
DROP TABLE IF EXISTS public.zillow_listings_raw;

CREATE TABLE IF NOT EXISTS public.zillow_listings_raw (
    zpid BIGINT NOT NULL,
    address VARCHAR(2000),
    unit VARCHAR(250),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    num_bedrooms INT,
    num_bathrooms NUMERIC, --Allow decimals for half bathrooms
    living_area NUMERIC(12, 1),
    lot_area_value NUMERIC(12, 1),
    lot_area_unit VARCHAR(10),
    price NUMERIC(12, 2),
    rent_zestimate NUMERIC(12, 2),
    zestimate NUMERIC(12, 2),
    has_3d_model BOOLEAN,
    has_video BOOLEAN,
    has_image BOOLEAN,
    property_type VARCHAR(50),
    listing_status VARCHAR(50),
    listing_subtype JSONB,
    detail_url VARCHAR(255),
    days_on_zillow INT,
    country VARCHAR(3),
    currency VARCHAR(3),
    extracted_at TIMESTAMP
);

DROP TABLE IF EXISTS public.zillow_property_details_raw;

CREATE TABLE IF NOT EXISTS public.zillow_property_details_raw (
    zpid BIGINT PRIMARY KEY,
    address JSONB,
    annual_homeowners_insurance NUMERIC,
    attribution_info JSONB,
    bathrooms NUMERIC,
    bedrooms INTEGER,
    broker_id VARCHAR(255),
    brokerage_name VARCHAR(255),
    building VARCHAR(255),
    building_id VARCHAR(255),
    building_permits JSONB,
    city VARCHAR(100),
    city_id INTEGER,
    climate JSONB,
    coming_soon_on_market_date DATE,
    contact_recipients JSONB,
    contingent_listing_type VARCHAR(255),
    country VARCHAR(100),
    county VARCHAR(100),
    county_fips VARCHAR(50),
    county_id INTEGER,
    currency VARCHAR(10),
    date_posted DATE,
    date_sold DATE,
    description TEXT,
    favorite_count INTEGER,
    home_facts JSONB,
    home_insights JSONB,
    home_status VARCHAR(100),
    home_type VARCHAR(100),
    img_src TEXT,
    is_listed_by_owner BOOLEAN,
    is_showcase_listing BOOLEAN,
    latitude DOUBLE PRECISION,
    listed_by JSONB,
    listing_provider VARCHAR(255),
    listing_sub_type JSONB,
    living_area NUMERIC,
    living_area_units VARCHAR(50),
    living_area_value NUMERIC,
    longitude DOUBLE PRECISION,
    mlsid VARCHAR(100),
    monthly_hoa_fee NUMERIC,
    mortgage_rates JSONB,
    mortgage_zhl_rates JSONB,
    nearby_homes JSONB,
    neighborhood_map_thumb JSONB,
    neighborhood_region JSONB,
    open_house_schedule JSONB,
    page_view_count INTEGER,
    photo_count INTEGER,
    price NUMERIC,
    price_change NUMERIC,
    price_change_date BIGINT,
    price_change_date_string DATE,
    price_history JSONB,
    property_tax_rate NUMERIC,
    property_type_dimension VARCHAR(100),
    provider_listing_id VARCHAR(255),
    rent_zestimate NUMERIC,
    reso_facts JSONB,
    schools JSONB,
    solar_potential JSONB,
    state VARCHAR(50),
    state_id INTEGER,
    street_address VARCHAR(255),
    tax_history JSONB,
    time_on_zillow VARCHAR(100),
    time_zone VARCHAR(100),
    url TEXT,
    year_built INTEGER,
    zestimate NUMERIC,
    zestimate_high_percent VARCHAR(50),
    zestimate_low_percent VARCHAR(50),
    zipcode VARCHAR(20),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

DROP TABLE IF EXISTS public.zip_codes;

CREATE TABLE IF NOT EXISTS public.zip_codes AS (
    zipcode VARCHAR(20),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    primary_city VARCHAR(100),
    state_province_code VARCHAR(2),
    state_name VARCHAR(100),
    population BIGINT,
    density NUMERIC,
    county_fips VARCHAR(5),
    county_name VARCHAR(50),
    county_weights JSONB,
    county_names_all VARCHAR(50),
    county_fips_all VARCHAR(50),
    timezone VARCHAR(50)
);